default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: heroku_pg_backup_s3_development

test:
  <<: *default
  database: heroku_pg_backup_s3_test

production:
  <<: *default
  database: heroku_pg_backup_s3_production
